[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_student_program = "HdBggj1AtyVj5gnM3Ru2A2dVXijFgQZQQX6i5q8xU3JN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
